apiVersion: v1
kind: Template
metadata:
  name: mongodb-backup-template
  annotations:
    description: 'Template for MongoDB container backup job'
    tags: 'database,backup,mongo'
objects:

  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${MONGODB_BACKUP_VOLUME_CLAIM}
    spec:
      storageClassName: ${MONGODB_STORAGE_CLASS}
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: ${VOLUME_CAPACITY}
      volumename: ${MONGODB_BACKUP_VOLUME_CLAIM}

  - apiVersion: batch/v1beta1
    kind: CronJob
    metadata:
      name: ${MONGODB_BACKUP_VOLUME_CLAIM}
    spec:
      schedule: ${MONGODB_BACKUP_SCHEDULE}
      concurrencyPolicy: Forbid
      jobTemplate:
        spec:
          template:
            spec:
              volumes:
                - name: ${MONGODB_BACKUP_VOLUME_CLAIM}
                  persistentVolumeClaim:
                    claimName: ${MONGODB_BACKUP_VOLUME_CLAIM}
              containers:
                - name: ${MONGODB_BACKUP_VOLUME_CLAIM}
                  image: 'docker-registry.default.svc:5000/openshift/mongodb:latest'
                  command:
                    - 'bash'
                    - '-c'
                    - >-
                      ls -rdt /var/lib/mongodb-backup/dump-* |
                      head -n -$MONGODB_BACKUP_KEEP |
                      xargs rm -rf &&
                      DIR=/var/lib/mongodb-backup/dump-`date +%F-%T` &&
                      mongodump -j 1 -u admin -p $MONGODB_ADMIN_PASSWORD --host $MONGODB_SERVICE_HOST --port $MONGODB_SERVICE_PORT --authenticationDatabase=admin --gzip --out=$DIR &&
                      echo &&
                      echo "To restore, use:" &&
                      echo "~# mongorestore -u admin -p \$MONGODB_ADMIN_PASSWORD --authenticationDatabase admin --gzip $DIR/DB_TO_RESTORE -d DB_TO_RESTORE_INTO"
                  resources:
                  limits:
                    cpu: 250m
                    memory: 1Gi
                  requests:
                    cpu: 100m
                    memory: 512Mi
                  env:
                    - name: MONGODB_BACKUP_KEEP
                      value: ${MONGODB_BACKUP_KEEP}
                    - name: MONGODB_ADMIN_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          key: admin-password
                          name: "${{MONGODB_SECRET_NAME}}"
                  volumeMounts:
                    - name: ${MONGODB_BACKUP_VOLUME_CLAIM}
                      mountPath: /var/lib/mongodb-backup
              restartPolicy: Never

parameters:

  - name: MONGODB_BACKUP_KEEP
    description: 'Number of backups to keep'
    value: '7'

  - name: MONGODB_BACKUP_SCHEDULE
    description: 'Cron-like schedule expression.'
    value: '0 2 * * *'

  - name: MONGODB_BACKUP_VOLUME_CLAIM
    description: 'Name of the volume claim to be used as storage'
    value: 'backup-mongo'

  - name: MONGODB_SECRET_NAME
    displayName: MongoDB Secret.
    description: Name of the Secret containing MongoDB Assets
    value: "mongodb"
    required: true

  - name: MONGODB_STORAGE_CLASS
    description: The Storage Class for the MongoDB
    displayName: Storage Class for MongoDB
    required: true
    value: "netapp-file-standard"

  - name: VOLUME_CAPACITY
    displayName: "Volume Capacity for MongoDB"
    required: true
