kind: Template
apiVersion: v1
metadata:
  name: rocket-chat
  annotations:
    description: "MongoDB replicate set for Cailey's Code Test."

objects:

  ## Mongo DB full list of secrets for admin access, app access and connection strings
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${MONGODB_SERVICE_NAME}
      labels:
        name: "${MONGODB_SERVICE_NAME}"
        project: "${PROJECT_NAME}"
        subproject: "mongodb"
    stringData:
      username: "${MONGODB_USER}"
      password: "${MONGODB_PASSWORD}"
      admin-username: "admin"
      admin-password: "${MONGODB_ADMIN_PASSWORD}"
      database: "${MONGODB_NAME}"
      replica-name: "${MONGODB_REPLICA_NAME}"
      mongo-url: "mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/${MONGODB_NAME}?replicaSet=${MONGODB_REPLICA_NAME}"
      mongo-oplog-url: "mongodb://admin:${MONGODB_ADMIN_PASSWORD}@${MONGODB_SERVICE_NAME}:27017/local?authSource=admin&replicaSet=${MONGODB_REPLICA_NAME}"

parameters:

  - name: MONGODB_SERVICE_NAME
    description: Name of the MongoDB Service
    displayName: MongoDB Service Name
    value: "mongodb"
    required: true

  - name: MONGODB_USER
    displayName: "MongoDB Connection Username"
    description: "Username for MongoDB user that will be used for accessing the database."
    generate: expression
    from: "[a-zA-Z0-9]{5}"
    required: true

  - name: MONGODB_PASSWORD
    displayName: "MongoDB Connection Password"
    description: "Password for the MongoDB connection user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_NAME
    displayName: "MongoDB Database Name"
    description: "Name of the MongoDB database accessed."
    value: rocketdb
    required: true

  - name: MONGODB_ADMIN_PASSWORD
    displayName: "MongoDB Admin Password"
    description: "Password for the database admin user."
    generate: expression
    from: "[a-zA-Z0-9]{16}"
    required: true

  - name: MONGODB_REPLICA_NAME
    displayName: "Replica Set Name"
    description: "The name of the replica set."
    value: rs0
    required: true

  - name: PROJECT_NAME
    displayName: Project's Name
    value: "code-test"
    required: true
